apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: Namespace
  labels:
    app: test

spec:
  containers:
  - name: hello-world
    image: dockercloud/hello-world
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
