---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    metadata:
      name: kubenetes-app
    spec:
      displayName: Service Account pour Kubernetes

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMPolicyMember
    metadata:
      name: policy-member-binding
    spec:
      member: serviceAccount:mytest@kubernetes-273408.iam.gserviceaccount.com
      role: roles/kubernetes.subscriber
      resourceRef:
        kind: Project
        name: kubernetes-273408
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
