apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: client
  namespace: wordpress
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-oath-adm
subjects:
- kind: User
  name: oath-admin
roleRef:
  kind: ClusterRole
  name: cluster-oath-admin
  apiGroup: rbac.authorization.k8s.io
---


